baseURL = "https://rvasdug.org/"
languageCode = "en-us"
title = "RVASDUG"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Sujith Paul"
    description = "RVA Software Development User Group"
    githubUsername = "rvasdug"
    accent = "lightseagreen"
    showBorder = true
    backgroundColor = "beige"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["java", "javascript", "go", "python", "shell"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/contact/"
    name = "Contact Us"
    weight = 3

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 4

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://www.meetup.com/rva-software-development-user-group/"
    name = "fab fa-meetup"
    weight = 1

[[menu.icon]]
    url = "https://rva-dev.slack.com/"
    name = "fab fa-slack"
    weight = 2

[[menu.icon]]
    url = "https://rva.fyi/@rvasdug"
    name = "fab fa-mastodon"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/rvasdug/"
    name = "fab fa-twitter"
    weight = 4

[[menu.icon]]
    url = "https://www.youtube.com/channel/UCn-ZV1RVYLmsRdgO3vXFpRQ/"
    name = "fab fa-youtube"
    weight = 5

[[menu.icon]]
    url = "https://github.com/rvasdug/"
    name = "fab fa-github"
    weight = 6

[[menu.icon]]
    url = "mailto:rvasdug@gmail.com"
    name = "fas fa-envelope"
    weight = 7
